### ISSUE TITLE
licensing issues

### ISSUE THREAD

**Issue by matkoniecz** [ideditor/imagery-index#5]
I wanted to remind about promised "so I'll just switch it to CC-BY-SA" from https://github.com/openstreetmap/iD/issues/7425#issuecomment-599132100 (14th March)

----

tl;dr:

offshot of https://github.com/openstreetmap/iD/issues/7425

This index is based on ELI, with some changes made to it, entry by entry. AFAIK making it a derivative work, what requires obeying license of the used materials.

I am basing it on description in https://github.com/openstreetmap/iD/issues/7425:

> all the files are significantly changed and I went through each one by hand and reworked the geometry

> I've had some time to dive in and clean up the editor-layer-index project

Note that "significantly changed" is not removing copyright. Manual editing is not enough to remove copyright.

And AFAIK ISC license of this repo is incompatible with CC-BY-SA, despite being a derivative work of CC-BY-SA materials.

In https://github.com/openstreetmap/iD/issues/7425#issuecomment-599132100 on 14th March it was promised that "so I'll just switch it to CC-BY-SA".

Both ELI maintainers and JOSM maintainers consider this as a license violation of the data shared between ELI and JOSM Imagery sources:  https://github.com/openstreetmap/iD/issues/7425#issuecomment-598059963 https://github.com/openstreetmap/iD/issues/7425#issuecomment-597946397

**Comment by bhousel** [comment]
Yes, you're correct @matkoniecz - I have fixed it to be like ELI's license.

Sorry I didn't get to it right away.. I was fired from my job and removed from the iD project, so the license change kind of slipped my mind.

**Comment by matkoniecz** [comment]
Thanks for the fix and I am really sorry about the situation, I was unaware about the context.

I hope that things are now going better.
